config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    post 'users/guest_sign_in' => 'users/sessions#guest_sign_in'
  end

  namespace :todo_lists do
    resources :searches, only: [:index]
  end

  namespace :documents do
    resources :searches, only: [:index]
  end

  root to: 'homes#top'
  get 'tutorial' => 'homes#tutorial'
  get 'policy' => 'homes#policy', as: :policy

  get 'users' => 'users#show', as: :my_page
  patch 'users/withdraw' => 'users#withdraw', as: :withdraw_user
  resources :users, only: [:update]

  # エラーメッセージ発生後にリロードするとエラーになるため指定
  get 'documents/:id' => 'documents#edit'
  resources :documents, only: [:create, :edit, :update, :destroy]

  resources :goals, only: [:create, :update, :destroy]

  get 'todo_lists/back' => 'todo_lists#back', as: :back_todo_lists
  get 'todo_lists/:id/check' => 'todo_lists#check', as: :check_todo_list
  delete 'todo_lists/delete_finished' => 'todo_lists#delete_finished', as: :delete_finished
  resources :todo_lists, except: [:new, :show]
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
  scope :classify, -> { order(:priority, :deadline) }

  belongs_to :goal
  belongs_to :user

  validates :body, { presence: true, length: { maximum: 100 } }
  validate :day_after_today

  # 過去の日付登録を防ぐバリデーション（期限超過の場合、期限変更かチェックを入れることだけできる）
  def day_after_today
    if !deadline.nil? && is_finished == false
      errors.add(:deadline, 'は、本日以降の日付を入力して下さい') if deadline.to_date < Date.current
    end
  end
end

app/controllers/todo_lists/searches_controller.rb
class TodoLists::SearchesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_current_user

  def index
    if params[:goal_id].blank? && params[:word].blank?
      todo_lists = @user.todo_lists
    elsif params[:goal_id].present? && params[:word].present?
      todo_lists = Goal.find(params[:goal_id]).todo_lists.where('body LIKE(?)', "%#{params[:word]}%")
    elsif params[:goal_id].present? && params[:word].blank?
      todo_lists = Goal.find(params[:goal_id]).todo_lists
    else
      todo_lists = @user.todo_lists.where('body LIKE(?)', "%#{params[:word]}%")
    end
    sort_lists = todo_lists.classify
    render partial: "todo_lists/todo_list", collection: sort_lists
  end

  private

  def set_current_user
    @user = current_user
  end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_current_user
  # index,back(indexへ戻る処理)以外はアクション実行後にソートしたいので、アクション内に記述
  before_action :set_user_todo_lists, only: [:index, :back]

  def index
    @document = Document.new
    @user_documents = @user.documents
    @user_level = @user_documents.sum(:add_level)

    @todo_list = TodoList.new

    @goal = Goal.new
    @goals = @user.goals.order("updated_at DESC")
    gon.goals = @goals.count
  end

  def back
  end

  def create
    @todo_list = TodoList.new(todo_list_params)
    @todo_list.user_id = @user.id
    deadline = params[:todo_list][:deadline]
    if deadline.blank?
      @todo_list.priority = 1
    end
    if @todo_list.save
      @todo_lists = @user.todo_lists.classify
    else
      render :todo_list_errors
    end
  end

  def edit
    @todo_list = TodoList.find(params[:id])
    @goals = @user.goals
  end

  def update
    @todo_list = TodoList.find(params[:id])
    deadline = params[:todo_list][:deadline]
    if deadline.present?
      @todo_list.priority = 0
    end
    if @todo_list.update(todo_list_params)
      @todo_lists = @user.todo_lists.classify
    else
      render :todo_list_errors
    end
  end

  def check
    @todo_list = TodoList.find(params[:id])
    if @todo_list.is_finished == false
      @todo_list.update_attributes(is_finished: true, priority: 2)
    elsif @todo_list.is_finished == true && @todo_list.deadline.nil?
      @todo_list.update_attributes(is_finished: false, priority: 1)
    else
      @todo_list.update_attributes(is_finished: false, priority: 0)
    end
    @todo_lists = @user.todo_lists.classify
  end

  def destroy
    todo_list = TodoList.find(params[:id])
    todo_list.destroy
    @todo_lists = @user.todo_lists.classify
  end

  def delete_finished
    @user.todo_lists.where(is_finished: true).delete_all
    @todo_lists = @user.todo_lists.classify
  end

  private

  def set_current_user
    @user = current_user
  end

  def set_user_todo_lists
    @todo_lists = @user.todo_lists.classify
  end

  def todo_list_params
    params.require(:todo_list).permit(:goal_id, :body, :deadline)
  end
end

app/helpers/todo_lists/searches_helper.rb
module TodoLists::SearchesHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
  def lists_with_deadline
    current_user.todo_lists.where(priority: 0)
  end

  def near_deadline_list_count
    today = Date.current
    after_3_days = today + 3
    lists_with_deadline.where(:deadline => today..after_3_days).count
  end

  def today_deadline_list_count
    lists_with_deadline.where(deadline: Date.current.all_day).count
  end

  def over_deadline_list_count
    yesterday = Date.current - 1
    lists_with_deadline.where("deadline < ?", yesterday).count
  end
end

app/views/todo_lists/_edit.html.erb
<%= form_with model: todo_list do |f| %>
  <div class="row">
    <div class="todo-lists__form--edit">
      <div class="form-inline todo-lists__form--area">
        <%= f.date_field :deadline %>
        <%= f.collection_select :goal_id, goals, :id, :category %>
      </div>
      <div class="form-inline todo-lists__form--area todo-lists__form--text">
        <%= f.text_field :body, size: 30 %>
      </div>
      <div class="form-inline todo-lists__form--area">
        <%= f.submit '＋', class: "todo-lists__link--update btn btn-primary btn-sm" %>
        <%= link_to "−", todo_list_path(todo_list.id), class: "todo-lists__link--destroy btn btn-danger btn-sm",
            method: :delete, "data-confirm" => "削除してよろしいですか？", remote: true %>
        <%= link_to back_todo_lists_path, class: "todo-lists__link--index", remote: true do %>
          <%= image_tag "icon/back-icon.png", class: "todo-lists__icon--back", alt: "back-icon" %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/todo_lists/_header.html.erb
<div class="todo-lists__header">
  <div class="form-group">
    <%= text_field_tag :word, '', class: 'js-todo-lists-search-field', placeholder: 'キーワードけんさく' %>
  </div>
  <h4 class="js-create-todo-lists__icon">
    <%= collection_select(:goal, :category, @goals, :id, :category, {prompt: "すべて"}, {class: "js-todo-lists-search-select"}) %>
    のTodoリスト
    <%= image_tag "icon/create-icon.png", class: "todo-lists__icon--create js-create-todo-lists-icon", alt: "create-icon" %>
    <%= image_tag "icon/quill-pen.png", class: "todo-lists__icon--create js-write-todo-lists-icon", alt: "write-icon" %>
  </h4>
  <div class="todo-lists__form--create js-todo-lists-form">
    <%= form_with model: @todo_list do |f| %>
      <div class="form-inline todo-lists__form--upper">
        <div class="form-group">
          <%= f.date_field :deadline %>
        </div>
        <div class="form-group">
          <%= f.collection_select :goal_id, @goals, :id, :category, {prompt: "もくひょう"} %>
        </div>
      </div>
      <div class="form-group todo-lists__form--text">
        <%= f.text_field :body, size: 35, placeholder: "やることを入力" %>
      </div>
      <div>
        <%= f.submit "ついか", class: "btn btn-primary btn-sm" %>
      </div>
      <p>※きげんは必須ではありません</p>
    <% end %>
  </div>
  <%= link_to "チェックずみをさくじょ", delete_finished_path, class: "btn btn-danger mb-3",
      method: :delete, "data-confirm" => "チェック済みのリストを全て削除してもよろしいですか？", remote: true %>
</div>

app/views/todo_lists/_todo_list.html.erb
<div id="list<%= todo_list.id %>-area">
  <div class="row">
    <div class="col-3">
      <% if todo_list.deadline.nil? %>
        <p>なし</p>
      <% else %>
        <%= todo_list.deadline.strftime("%m/%d") %>
      <% end %>
    </div>
    <div class="col-7">
      <% if todo_list.is_finished == true %>
        <p>
          <del class="todo-lists__finished"><%= todo_list.body %></del>
        </p>
      <% else %>
        <%= link_to edit_todo_list_path(todo_list.id), class: "todo-lists__link--edit", remote: true do %>
          <!-- 未完了かつ期限付きのリストの場合、期限までの期間によって条件分岐 -->
          <% if todo_list.deadline.present? %>
            <% case (todo_list.deadline.to_date - Date.current) %>
            <% when 4..nil %>
              <p class="todo-lists__not-finished"><%= todo_list.body %></p>
            <!-- 期限が3日以内または期限超過の場合、背景色が変化 -->
            <% when 1..3 %>
              <div class="todo-lists__nead-deadline">
                <p class="todo-lists__not-finished"><%= todo_list.body %></p>
              </div>
            <% when 0 %>
              <div class="todo-lists__today-deadline">
                <p class="todo-lists__not-finished"><%= todo_list.body %></p>
              </div>
            <% else %>
              <div class="todo-lists__over-deadline">
                <p class="todo-lists__not-finished"><%= todo_list.body %></p>
              </div>
            <% end %>
          <% else %>
            <p class="todo-lists__not-finished"><%= todo_list.body %></p>
          <% end %>
        <% end %>
      <% end %>
    </div>
    <div class="col-2">
      <%= link_to check_todo_list_path(todo_list.id), remote: true do %>
        <% if todo_list.is_finished == true %>
          <%= image_tag "icon/checked-icon.png", class: "todo-lists__icon--check", alt: "check-icon" %>
        <% else %>
          <%= image_tag "icon/not-checked-icon.png", class: "todo-lists__icon--check", alt: "checkbox-icon" %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/todo_lists/back.js.erb
$(".js-todo-lists").html("<%= j(render @todo_lists) %>");
$(".error__message").remove();

app/views/todo_lists/check.js.erb
$(".js-todo-lists").html("<%= j(render @todo_lists) %>");

app/views/todo_lists/create.js.erb
$(".js-todo-lists").html("<%= j(render @todo_lists) %>");
$("#todo_list_body, #todo_list_goal_id, #todo_list_deadline").val("");
$(".error__message").remove();

app/views/todo_lists/delete_finished.js.erb
$(".js-todo-lists").html("<%= j(render @todo_lists) %>");
$(".error__message").remove();

app/views/todo_lists/destroy.js.erb
$(".js-todo-lists").html("<%= j(render @todo_lists) %>");
$(".error__message").remove();

app/views/todo_lists/edit.js.erb
$("#list<%= @todo_list.id %>-area").html("<%= j(render 'todo_lists/edit', todo_list: @todo_list, goals: @goals) %>");
$("#todo_list_body").val("");
$(".error__message").remove();

app/views/todo_lists/index.html.erb
<div class="todo-lists">
  <div class="todo-lists__notice">
    <% if near_deadline_list_count >= 1 %>
      <div class="todo-lists__notice--near-deadline">
        <p class="todo-lists__notice--text">きげんが近いものが&nbsp;<%= near_deadline_list_count %>&nbsp;つあります</p>
      </div>
    <% end %>
    <% if today_deadline_list_count >= 1 %>
      <div class="todo-lists__notice--today-deadline">
        <p class="todo-lists__notice--text">きげんが本日のものが&nbsp;<%= today_deadline_list_count %>&nbsp;つあります</p>
      </div>
    <% end %>
    <% if over_deadline_list_count >= 1 %>
      <div class="todo-lists__notice--over-deadline">
        <p class="todo-lists__notice--text">きげん切れのものが&nbsp;<%= over_deadline_list_count %>&nbsp;つあります</p>
      </div>
    <% end %>
    <% if near_deadline_list_count >= 1 || today_deadline_list_count >= 1 || over_deadline_list_count >= 1 %>
      <p class="todo-lists__notice--text">※Todoリストを修正後、ページを再読み込みすることで通知が更新されます</p>
    <% end %>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-lg-3 col-md-0 col-sm-0">
        <%= render "layouts/side_menu", goals: @goals %>
        <div class="my-page__menu--icon js-todo-list-icon">
          <%= link_to my_page_path do %>
            <%= image_tag "icon/door.png", class: "my-page__menu--icon-img", alt: "menu-icon" %></br>
            <p class="my-page__link--text">マイページ</p>
          <% end %>
        </div>
      </div>
      <div class="col-lg-9 col-md-12 col-sm-12">
        <h3 class="master message upper-contents">やることをまとめるのじゃ！</h3>
        <div class="js-list-errors"></div>
        <%= render "todo_lists/header", goals: @goals, todo_list: @todo_list %>
        <div class="todo-lists__index">
          <div class="container">
            <div class="row">
              <div class="col-3">きげん</div>
              <div class="col-7">やること</div>
              <div class="col-2">
                <%= image_tag "icon/check-icon.png", class: "todo-lists__icon--check", alt: "check-icon" %>
              </div>
            </div>
            <div class="js-todo-lists">
              <%= render @todo_lists %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/todo_lists/todo_list_errors.js.erb
$('.error__message').remove();
$('.js-list-errors').append("<%= j(render 'layouts/validation_errors',obj: @todo_list) %>");

app/views/todo_lists/update.js.erb
$(".js-todo-lists").html("<%= j(render @todo_lists) %>");
$(".error__message").remove();