config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    post 'users/guest_sign_in' => 'users/sessions#guest_sign_in'
  end

  namespace :todo_lists do
    resources :searches, only: [:index]
  end

  namespace :documents do
    resources :searches, only: [:index]
  end

  root to: 'homes#top'
  get 'tutorial' => 'homes#tutorial'
  get 'policy' => 'homes#policy', as: :policy

  get 'users' => 'users#show', as: :my_page
  patch 'users/withdraw' => 'users#withdraw', as: :withdraw_user
  resources :users, only: [:update]

  # エラーメッセージ発生後にリロードするとエラーになるため指定
  get 'documents/:id' => 'documents#edit'
  resources :documents, only: [:create, :edit, :update, :destroy]

  resources :goals, only: [:create, :update, :destroy]

  get 'todo_lists/back' => 'todo_lists#back', as: :back_todo_lists
  get 'todo_lists/:id/check' => 'todo_lists#check', as: :check_todo_list
  delete 'todo_lists/delete_finished' => 'todo_lists#delete_finished', as: :delete_finished
  resources :todo_lists, except: [:new, :show]
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :rememberable,
         :validatable, :omniauthable, omniauth_providers: %i(google_oauth2 facebook twitter)

  has_many :documents, dependent: :destroy
  has_many :goals, dependent: :destroy
  has_many :todo_lists, dependent: :destroy

  validates :name, { presence: true, length: { maximum: 60 } }
  validates :email, { presence: true, uniqueness: true }

  attachment :profile_image

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゆうしゃ"
    end
  end

  def self.from_omniauth(auth)
    find_or_create_by!(email: auth.info.email) do |user|
      user.name = auth.info.email
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    callback_for(:google)
  end

  def facebook
    callback_for(:facebook)
  end

  def twitter
    callback_for(:twitter)
  end

  def callback_for(provider)
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if !@user.is_active
      flash[:alert] = 'このアカウントは退会済みです。お手数ですが、別のアカウントをお使いください。'
      redirect_to new_user_session_path
    elsif @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      flash[:notice] = "#{provider}アカウントでログインしました"
    else
      redirect_to new_user_registration_path
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  def create
    super
    WelcomeMailer.send_when_signup(params[:user][:email],params[:user][:name]).deliver
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :reject_inactive_user, only: [:create]

  def guest_sign_in
    user = User.guest
    sign_in user
    flash[:notice] = "ゲストでログインしました"
    redirect_to my_page_path
  end

  def reject_inactive_user
    @user = User.find_by(email: params[:user][:email])
    if @user
      if @user.valid_password?(params[:user][:password]) && !@user.is_active
        flash[:alert] = 'このアカウントは退会済みです。お手数ですが、別のメールアドレスをお使いください。'
        redirect_to new_user_session_path
      end
    end
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_current_user
  before_action :ensure_normal_user, only: :withdraw

  def show
    @document = Document.new
    @documents = @user.documents.includes(:goal).page(params[:page]).per(6).reverse_order

    @user_documents = @user.documents
    @user_level = @user_documents.sum(:add_level)

    @goal = Goal.new
    @goals = @user.goals.order("updated_at DESC")

    gon.goals = @goals.count
    gon.documents = @documents.count
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        # S3への画像反映のタイムラグを考慮して3秒待機
        sleep(3)
        flash[:notice] = "データをへんこうしました"
        format.html { redirect_to my_page_path }
      else
        format.js { render "user_errors" }
      end
    end
  end

  def withdraw
    @user.update(is_active: false)
    reset_session
    redirect_to root_path
  end

  private

  def set_current_user
    @user = current_user
  end

  def ensure_normal_user
    if @user.email == 'guest@example.com'
      flash[:alert] = "ゲストはさくじょできません"
      redirect_to my_page_path
    end
  end

  def user_params
    params.require(:user).permit(:name, :profile_image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def clear_count
    goals = current_user.goals
    goals.where("level >= ?", 100).count
  end
end

app/views/users/_edit.html.erb
<div id="modal-user-edit" class="modal js-modal">
  <div class="modal__back js-modal-close"></div>
  <div class="modal__content">
    <div class="user-edit">
      <div class="container">
        <div class="row">
          <div class="col-lg-1 col-md-1 col-sm-0"></div>
          <div class="col-lg-10 col-md-10 col-sm-12 user-edit-form">
            <div class="js-user-edit">
              <h3 class="princess message upper-contents">
                あなたのことを<br>
                おしえてくれますか？
              </h3>
              <div class="js-message-errors"></div>
              <%= form_with model: user, url: user_path(current_user.id), method: :patch, remote: true do |f| %>
                <div class="form-group mt-2">
                  <label for="inputName">なまえ</label><br>
                  <%= f.text_field :name, class: "user-edit__form--name", placeholder: "名前" %>
                </div>
                <div class="form-group">
                  <label for="inputImage">プロフィールがぞう</label>
                  <%= f.attachment_field :profile_image, class: "form-control-file user-edit__form--image" %>
                </div>
                <%= f.submit 'へんこう', class: "btn btn-primary btn-sm mt-3" %>
                <a href="" class="btn btn-danger btn-sm mt-3 ml-5 js-withdraw-btn">退会する</a>
              <% end %>
            </div>
            <div class="js-withdraw-confirm withdraw-confirm">
              <p class="withdraw-confirm__text">
                退会するとこれまでのきろくなどの<br>
                データが全てなくなります。<br>
                元にもどすことはできませんが、よろしいですか？
              </p>
              <%= link_to "退会する", withdraw_user_path, method: :patch, class: "btn btn-danger btn-sm",
                  "data-confirm" => "OKを押すと退会処理がされます。本当によろしいですか？" %>
              <a href="" class="btn btn-primary btn-sm ml-5 js-user-edit-btn">もどる</a>
            </div>
          </div>
          <div class="col-lg-1 col-md-1 col-sm-0"></div>
        </div>
      </div>
    </div>
    <a class="js-modal-close" href="">閉じる</a>
  </div>
</div>

app/views/users/edit.html.erb
<div class="user-edit">
  <div class="container">
    <div class="row">
      <div class="col-lg-3 col-md-2 col-sm-0"></div>
      <div class="col-lg-6 col-md-8 col-sm-12 user-edit-form">
        <h2 class="master-message">おぬしのことをおしえて </br>
        くれんかの？</h2>

        <% if @user.errors.any? %>
          <div class="error-explanation">
            <h3><%= pluralize(@user.errors.count,"つの") %>エラーがあります</h3>
              <ul class="error-message">
                <% @user.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
          </div>
        <% end %>

        <%= form_with model: @user, local:true do |f| %>
          <div class="form-group mt-2">
            <label for="inputName">なまえ</label>
            <%= f.text_field :name, class: "form-control", placeholder: "名前" %>
          </div>
          <div class="form-group">
            <label for="inputImage">プロフィールがぞう</label>
            <%= f.attachment_field :profile_image, class: "form-control-file" %>
          </div>
          <div class="form-btn">
            <%= f.submit 'へんこう', class: "btn btn-primary btn-sm" %>
          </div>
        <% end %>
          <div class="new-goal-link">
            <%= link_to "もくひょうをせっていする", new_goal_path %>
          </div>
      </div>

      <div class="col-lg-3 col-md-2 col-sm-0"></div>

    </div>
  </div>
</div>

app/views/users/errors.js.erb
$('.js-message-errors').replaceWith(
  "<%= j(
    render 'layouts/validation_errors',
    instance: @user
  ) %>"
);

app/views/users/show.html.erb
<div class="my-page">
  <%= render "layouts/level_up_flash" %>
  <%= render "layouts/clear_flash" %>
  <%= render "layouts/deadline_alert.html" %>
  <div class="container">
    <div class="row">
      <div class="col-lg-3 col-md-0 col-sm-0">
        <p class="my-page__message my-page__message--notice"><%= flash[:notice] %></p>
        <p class="my-page__message my-page__message--alert"><%= flash[:alert] %></p>
        <%= render "layouts/side_menu", goals: @goals %>
        <div class="my-page__menu--icon js-todo-list-icon">
          <%= link_to todo_lists_path, class: "js-todo-list-link" do %>
            <%= image_tag "icon/bar-icon.png", class: "my-page__menu--icon-img", alt: "menu-icon" %><br>
            <p class="my-page__link--text">Todoリスト</p>
          <% end %>
        </div>
      </div>
      <div class="col-lg-9 col-md-12 col-sm-12">
        <% if current_user.documents.exists? then %>
          <h3 class="master message upper-contents">これまでのきろくじゃ</h3>
          <div class="doc-card__search">
            <%= form_with url: documents_searches_path, method: :get, local: true do |f| %>
              <%= f.collection_select :goal_id, @goals, :id, :category, { prompt: "すべてのもくひょう" } %>
              <%= f.text_field :word, placeholder: 'キーワードを入力' %>
              <%= f.submit "けんさく", class: "btn btn-sm btn-success" %>
            <% end %>
          </div>
        <% elsif @goals.blank? then %>
          <h3 class="master message upper-contents">
            まずは「もくひょう」をおして<br>
            せっていしてみるのじゃ！
          </h3>
        <% else %>
          <h3 class="master message upper-contents">
            つぎは「きろくする」をおして<br>
            とうこうしてみるのじゃ！
          </h3>
        <% end %>
        <%= render "documents/card", documents: @documents %>
      </div>
    </div>
  </div>
</div>

app/views/users/user_errors.js.erb
$('.error__message').remove();
$('.js-message-errors').append("<%= j(render 'layouts/validation_errors',obj: @user) %>");