config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    post 'users/guest_sign_in' => 'users/sessions#guest_sign_in'
  end

  namespace :todo_lists do
    resources :searches, only: [:index]
  end

  namespace :documents do
    resources :searches, only: [:index]
  end

  root to: 'homes#top'
  get 'tutorial' => 'homes#tutorial'
  get 'policy' => 'homes#policy', as: :policy

  get 'users' => 'users#show', as: :my_page
  patch 'users/withdraw' => 'users#withdraw', as: :withdraw_user
  resources :users, only: [:update]

  # エラーメッセージ発生後にリロードするとエラーになるため指定
  get 'documents/:id' => 'documents#edit'
  resources :documents, only: [:create, :edit, :update, :destroy]

  resources :goals, only: [:create, :update, :destroy]

  get 'todo_lists/back' => 'todo_lists#back', as: :back_todo_lists
  get 'todo_lists/:id/check' => 'todo_lists#check', as: :check_todo_list
  delete 'todo_lists/delete_finished' => 'todo_lists#delete_finished', as: :delete_finished
  resources :todo_lists, except: [:new, :show]
end

app/models/goal.rb
class Goal < ApplicationRecord
  belongs_to :user
  belongs_to :stage
  has_many :documents, dependent: :destroy
  has_many :todo_lists, dependent: :destroy

  validates :category, { presence: true, length: { maximum: 20 } }
  validates :goal_status, { presence: true, length: { maximum: 100 } }
  validates :deadline, presence: true
  validate :day_after_today

  def day_after_today
    unless deadline.nil?
      errors.add(:deadline, 'は、本日以降の日付を入力して下さい') if deadline.to_date < Date.current
    end
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :authenticate_user!

  def create
    @goal = Goal.new(goal_params)
    @goal.user_id = current_user.id
    respond_to do |format|
      if @goal.save
        flash[:notice] = "もくひょうをついかしました"
        format.html { redirect_to my_page_path }
      else
        format.js { render "goal_errors" }
      end
    end
  end

  def update
    @goal = Goal.find(params[:id])
    respond_to do |format|
      if @goal.update(goal_params)
        flash[:notice] = "もくひょうをへんこうしました"
        format.html { redirect_to my_page_path }
      else
        format.js { render "goal_errors" }
      end
    end
  end

  def destroy
    goal = Goal.find(params[:id])
    goal.destroy
    flash[:notice] = "もくひょうをさくじょしました"
    redirect_to my_page_path
  end

  private

  def goal_params
    params.require(:goal).permit(:category, :goal_status, :deadline, :level, :stage_id, :doc_count)
  end
end

app/helpers/goals_helper.rb
module GoalsHelper
  def latest_milestone(goal_id)
    documents = Document.where(goal_id: goal_id).order(updated_at: :desc)
    documents.first.milestone
  end

  def goals_not_cleared
    current_user.goals.where("level < ?", 100)
  end

  def near_deadline_goal_count
    today = Date.current
    after_3_days = today + 3
    goals_not_cleared.where(:deadline => today..after_3_days).count
  end

  def today_deadline_goal_count
    goals_not_cleared.where(deadline: Date.current.all_day).count
  end

  def over_deadline_goal_count
    yesterday = Date.current - 1
    goals_not_cleared.where("deadline < ?", yesterday).count
  end
end

app/views/goals/_edit.html.erb
<div id="modal-goal<%= goal.id %>-edit" class="modal js-modal">
  <div class="modal__back js-modal-close"></div>
  <div class="modal__content">
    <div class="goal-edit">
      <div class="container">
        <div class="row">
          <div class="col-lg-2 col-md-1 col-sm-0"></div>
          <div class="col-lg-8 col-md-10 col-sm-12">
            <h3 class="witch message upper-contents">もくひょうのへんこうかしら？</h3>
            <div class="js-message-errors"></div>
            <div class="form-group">
              <% if goal.present? %>
                <%= form_with model: goal do |f| %>
                  <label for="inputCategory">レベルアップしたいこと</label>
                  <!-- goals/newの部分テンプレート内のフォームのidと重複しないよう、idを指定 -->
                  <%= f.text_field :category, class: "form-control", id: "edit-goal#{goal.id}-category",
                      placeholder: "レベルアップしたいこと" %>
                  <label for="inputGoalStatus">さいしゅうもくひょう</label>
                  <%= f.text_field :goal_status, class: "form-control", id: "edit-goal#{goal.id}-goal_status",
                      placeholder: "Lv.100のじょうたい" %>
                  <label for="inputDeadline">きげん</label>
                  <%= f.date_field :deadline, class: "form-control", id: "edit-goal#{goal.id}-deadline" %>
                  <%= f.submit 'へんこう', class: "btn btn-primary btn-sm mt-3 ml-5" %>
                  <%= link_to "さくじょ", goal_path(goal.id), method: :delete, class: "btn btn-danger btn-sm mt-3 ml-5",
                      "data-confirm" => "関連する投稿も削除されます。本当によろしいですか？" %>
                <% end %>
              <% else %>
                <p>もくひょうがせっていされていません</p>
              <% end %>
            </div>
          </div>
          <div class="col-lg-2 col-md-1 col-sm-0"></div>
        </div>
      </div>
    </div>
    <a class="js-modal-close" href="">閉じる</a>
  </div>
</div>

app/views/goals/_new.html.erb
<div id="modal-new-goal" class="modal js-modal">
  <div class="modal__back js-modal-close"></div>
  <div class="modal__content">
　  <div class="new-goal">
      <div class="container">
        <div class="row">
          <div class="col-lg-2 col-md-0 col-sm-0"></div>
          <div class="col-lg-8 col-md-12 col-sm-12">
            <h3 class="knight message upper-contents">もくひょうをきめるのよ</h3>
            <div class="js-message-errors"></div>
            <%= form_with model: goal, remote: true do |f| %>
              <div class="form-group">
                <label for="inputCategory">レベルアップしたいこと</label>
                <%= f.text_field :category, class: "form-control", placeholder: "レベルアップしたいこと" %>
              </div>
              <div class="form-group">
                <label for="inputGoalStatus">さいしゅうもくひょう</label>
                <%= f.text_field :goal_status, class: "form-control", placeholder: "Lv.100のじょうたい" %>
              </div>
              <div class="form-group">
                <label for="inputDeadline">きげん</label>
                <%= f.date_field :deadline, class: "form-control" %>
              </div>
              <div class="form-btn">
                <%= f.submit 'せってい', class: "btn btn-primary btn-sm" %>
              </div>
            <% end %>
          </div>
          <div class="col-lg-2 col-md-0 col-sm-0"></div>
        </div>
      </div>
    </div>
    <a class="js-modal-close" href="">閉じる</a>
  </div>
</div>

app/views/goals/edit.html.erb
<div class="goal-edit">
  <div class="container">
    <div class="row">
      <div class="col-lg-3 col-md-2 col-sm-0"></div>
      <div class="col-lg-6 col-md-8 col-sm-12 goal-post-form">
        <h3 class="master-message upper-contents">もくひょうをへんこうできるぞ</h3>
        <div class="form-group">
          <%= render "layouts/validation_errors", instance: @goal %>
            <% if @goal.present? %>
              <%= form_with model: @goal, local:true do |f| %>
          	    <label for="inputCategory">レベルアップしたいこと</label>
                <%= f.text_field :category, class: "form-control", placeholder: "レベルアップしたいこと" %>
                <label for="inputGoalStatus">さいしゅうもくひょう</label>
                <%= f.text_field :goal_status, class: "form-control", placeholder: "どうなっていたいか" %>
                <label for="inputDeadline">きげん</label>
                <%= f.date_select :deadline, class: "form-control" %>
                <%= f.submit 'へんこう', class: "btn btn-primary btn-sm" %>
              <% end %>
              <%= link_to "さくじょ", goal_path(@goal.id), method: :delete,
                  "data-confirm" => "関連する投稿も削除されます。本当によろしいですか？", class: "btn btn-danger btn-sm"  %>
            <% else %>
              <p>もくひょうがせっていされていません。</br>
              あたらしくせっていしますか？</p>
              <%= link_to "はい  ", new_goal_path %>
              <%= link_to "いいえ", user_path(current_user.id) %>
            <% end %>
        </div>
      </div>

      <div class="col-lg-3 col-md-2 col-sm-0"></div>

    </div>
  </div>
</div>

app/views/goals/edit.js.erb
$("<%= render "goals/show", goal: @goal %>").replaceWith("<%= j(render 'goals/edit') %>");

app/views/goals/goal_errors.js.erb
$('.error__message').remove();
$('.js-message-errors').append("<%= j(render 'layouts/validation_errors',obj: @goal) %>");

app/views/goals/new.html.erb
<div class="goal-new">
  <div class="container">
    <div class="row">
      <div class="col-lg-3 col-md-2 col-sm-0"></div>
      <div class="col-lg-6 col-md-8 col-sm-12 goal-post-form">
        <h2 class="master-message">もくひょうをきめるのじゃ！</h2>
        <% if @goal.errors.any? %>
          <div class="error-explanation">
            <h3><%= pluralize(@goal.errors.count,"つの") %>エラーがあります</h3>
              <ul class="error-message">
                <% @goal.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
          </div>
        <% end %>
            <%= form_with model: @goal, local:true do |f| %>
              <div class="form-group">
                <label for="inputCategory">レベルアップしたいこと</label>
                <%= f.text_field :category, class: "form-control", placeholder: "レベルアップしたいこと" %>
              </div>
              <div class="form-group">
                <label for="inputGoalStatus">さいしゅうもくひょう</label>
                <%= f.text_field :goal_status, class: "form-control", placeholder: "どうなっていたいか" %>
              </div>
              <div class="form-group">
                <label for="inputDeadline">きげん</label>
                <%= f.date_select :deadline, class: "form-control" %>
              </div>
              <div class="form-btn">
                <%= f.submit 'せってい', class: "btn btn-primary btn-sm" %>
              </div>
            <% end %>
      </div>
      <div class="col-lg-3 col-md-2 col-sm-0"></div>
    </div>
  </div>
</div>

app/views/goals/show.html.erb
<div class="goal-show">
  <div class="container">
    <div class="row">
      <div class="col-lg-3 col-md-2 col-sm-0"></div>
      <div class="col-lg-6 col-md-8 col-sm-12 goal-post-form">
        <h3 class="master-message upper-contents">もくひょうのかくにんは</br>
        たいせつじゃな</h3>
        <div>
        	<p>レベルアップしたいこと</p>
        	<h3><%= @goal.category %></h3>
        	<p>さいしゅうもくひょう</p>
        	<h3><%= @goal.goal_status %></h3>
        	<p>いつまでに</p>
        	<h3><%= @goal.deadline.strftime('%Y/%m/%d') %></h3>
        	<p>げんざいのレベル</p>
        	<%= link_to "へんこう", edit_goal_path(@goal.id) %>
        </div>
       </div>
       <div class="col-lg-3 col-md-2 col-sm-0"></div>
    </div>
  </div>
</div>