config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    post 'users/guest_sign_in' => 'users/sessions#guest_sign_in'
  end

  namespace :todo_lists do
    resources :searches, only: [:index]
  end

  namespace :documents do
    resources :searches, only: [:index]
  end

  root to: 'homes#top'
  get 'tutorial' => 'homes#tutorial'
  get 'policy' => 'homes#policy', as: :policy

  get 'users' => 'users#show', as: :my_page
  patch 'users/withdraw' => 'users#withdraw', as: :withdraw_user
  resources :users, only: [:update]

  # エラーメッセージ発生後にリロードするとエラーになるため指定
  get 'documents/:id' => 'documents#edit'
  resources :documents, only: [:create, :edit, :update, :destroy]

  resources :goals, only: [:create, :update, :destroy]

  get 'todo_lists/back' => 'todo_lists#back', as: :back_todo_lists
  get 'todo_lists/:id/check' => 'todo_lists#check', as: :check_todo_list
  delete 'todo_lists/delete_finished' => 'todo_lists#delete_finished', as: :delete_finished
  resources :todo_lists, except: [:new, :show]
end

app/views/layouts/_clear_flash.html.erb
<% if flash[:clear] %>
  <div class="clear__back">
    <div class="fireworks fireworks-left">
      <%= image_tag "fireworks.png", alt: "flash-image" %>
    </div>
    <div class="fireworks fireworks-center">
      <%= image_tag "fireworks.png", alt: "flash-image" %>
    </div>
    <div class="fireworks fireworks-right">
      <%= image_tag "fireworks.png", alt: "flash-image" %>
    </div>
    <div class="fireworks fireworks-under-right">
      <%= image_tag "red-fireworks.png", alt: "flash-image" %>
    </div>
    <div class="fireworks fireworks-under-left">
      <%= image_tag "red-fireworks.png", alt: "flash-image" %>
    </div>
    <div class="levelup__char">
      <%= image_tag "character/brave.png", alt: "flash-image" %>
      <%= image_tag "character/witch.png", alt: "flash-image" %>
      <%= image_tag "character/priest.png", alt: "flash-image" %>
      <%= image_tag "character/princess.png", alt: "flash-image" %>
    </div>
    <p class="clear__text message"><%= flash[:clear] %></p>
    <p class="levelup__text">LEVELUP!</p>
    <p class="clear__text-bottom knight message">
      もくひょうたっせいおめでとう！<br>
      あなたは立派なゆうしゃよ！！
    </p>
    <a class="js-close-flash clear__link" href="">マイページへもどる</a>
    <div id="js-countdown"></div>
  </div>
  <!-- フラッシュ表示時のみカウントダウンが動くようview内に記載 -->
  <%= javascript_include_tag 'countdown' %>
<% end %>

app/views/layouts/_deadline_alert.html.erb
<div class="my-page__notice">
  <% if near_deadline_goal_count >= 1 %>
    <div class="my-page__notice--near-deadline">
      <p class="my-page__notice--text">きげんが近いもくひょうが&nbsp;<%= near_deadline_goal_count %>&nbsp;つあります</p>
    </div>
  <% end %>
  <% if today_deadline_goal_count >= 1 %>
    <div class="my-page__notice--today-deadline">
      <p class="my-page__notice--text">きげんが本日のもくひょうが&nbsp;<%= today_deadline_goal_count %>&nbsp;つあります</p>
    </div>
  <% end %>
  <% if over_deadline_goal_count >= 1 %>
    <div class="my-page__notice--over-deadline">
      <p class="my-page__notice--text">
        きげん切れのもくひょうが&nbsp;<%= over_deadline_goal_count %>&nbsp;つあるため、きげんを修正してください
      </p>
    </div>
  <% end %>
  <% if near_deadline_list_count >= 1 || today_deadline_list_count >= 1 || over_deadline_list_count >= 1 %>
    <div class="my-page__notice-list--area">
      <p class="my-page__notice-list--text">きげん切れ、またはきげんが近づいているTodoリストがあります</p>
      <%= link_to "かくにんする", todo_lists_path, class: "my-page__link--text" %>
    </div>
  <% end %>
</div>

app/views/layouts/_header.html.erb
<header class="header">
  <h2>
    <%= link_to "Dot Diary", root_path, class: "header__link header__title" %>
    <span class="header__sub-title">〜みっかぼうずのやぼう〜</span>
  </h2>
  <div class="js-menu header__menu">
    <ul class="header__menu--list">
      <% if user_signed_in? %>
        <li>
          <%= link_to "マイページ", my_page_path, class: "header__link" %>
        </li>
        <li>
          <%= link_to "あそびかた", "/tutorial", class: "header__link" %>
        </li>
        <li>
          <%= link_to "プライバシーポリシー", policy_path, class: "header__link" %>
        </li>
        <li>
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "header__link" %>
        </li>
      <% else %>
        <li>
          <%= link_to "あそびかた", "/tutorial", class: "header__link" %>
        </li>
        <li>
          <!-- 一部iphone端末で新規登録画面のみ接続エラーが起きる為、turbolinksを無効化 -->
          <%= link_to "あたらしくはじめる", new_user_registration_path, class: "header__link", data: {"turbolinks"=>false} %>
        </li>
        <li>
          <%= link_to "つづきから", new_user_session_path, class: "header__link" %>
        </li>
        <li>
          <%= link_to "ゲストログイン", users_guest_sign_in_path, method: :post, class: "header__link" %>
        </li>
        <li>
          <%= link_to "プライバシーポリシー", policy_path, class: "header__link" %>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="header__trigger--area">
    <a class="js-menu-trigger header__link header__trigger--link" href="">
      MENU
    </a>
  </div>
</header>

app/views/layouts/_level_up_flash.html.erb
<% if flash[:level_up] %>
  <div class="levelup__back">
    <div class="levelup__char">
      <%= image_tag "character/brave.png", alt: "flash-image" %>
      <%= image_tag "character/witch.png", alt: "flash-image" %>
      <%= image_tag "character/priest.png", alt: "flash-image" %>
      <%= image_tag "character/princess.png", alt: "flash-image" %>
    </div>
    <p class="levelup__text"></p>
    <p class="levelup__text-bottom brave message">
      <%= flash[:level_up] %>
    </p>
  </div>
<% end %>

app/views/layouts/_side_menu.html.erb
<p class="my-page__menu--logo upper-contents">&nbsp;M&nbsp;E&nbsp;N&nbsp;U&nbsp;</p>
<!-- ユーザーメニュー -->
<div class="my-page__menu--icon js-menu-icon">
  <%= attachment_image_tag @user, :profile_image, size: "100x100", fallback: "character/brave.png",
      class: "my-page__menu--icon-img", alt: "menu-icon" %>
  <p class="my-page__menu--text">しゅじんこう</p>
</div>
<div class="my-page__menu">
  <p>なまえ: <%= @user.name %></p>
  <p class="user-level">ステータス: Lv.<%= @user_level %></p>
  <p class="doc-count">ぼうけん: <%= @user_documents.count %> 回</p>
  <p>クリア: <%= clear_count %> 回</p>
  <a class="js-modal-open my-page__link--text" href="" data-target="modal-user-edit">へんしゅう</a>
  <!-- モーダルウインドウ -->
  <%= render "users/edit", user: @user %>
</div>
<!-- 目標メニュー -->
<div class="my-page__menu--icon js-menu-icon">
  <%= image_tag "icon/books.png", class: "my-page__menu--icon-img my-page__menu--icon--goal", alt: "menu-icon" %>
  <p class="my-page__menu--text">もくひょう </p>
</div>
<div class="my-page__menu">
  <% if @goals.exists? %>
    <% @goals.includes(:stage).first(3).each do |goal| %>
      <a class="js-modal-open my-page__menu--text-goal" href="" data-target="modal-goal<%= goal.id %>-edit">
        <%= goal.category %> <br>
        Lv.<%= goal.level %>
      </a>
      <p>
        ステージ: <%= goal.doc_count %>F<br>
        <% if goal.doc_count != 0 %>
          <%= goal.stage.name %>
        <% else %>
          きろくなし
        <% end %>
      </p>
      <p>
        つぎのもくひょう:<br>
        <% if goal.documents.exists? %>
          <%= latest_milestone(goal.id) %>
        <% else %>
          <a class="js-modal-open my-page__link--text" href="" data-target="modal-new-doc">ぼうけんをきろくする</a>
        <% end %>
      </p>
    <% end %>
    <!-- モーダルウインドウ -->
    <% @goals.each do |goal| %>
      <%= render "goals/edit", goal: goal %>
    <% end %>
    <!-- 目標が4つ以上の場合にセレクトボックス表示-->
    <%= collection_select(:goal, :category, @goals.drop(3), :id, :category,
        {prompt: "その他のもくひょう"}, {class: "js-menu-goal-select"}) %><br>
  <% else %>
    <p class="my-page__menu--text-goal">みせってい</p>
  <% end %>
  <!-- モーダルウインドウ -->
  <%= render "goals/new", goal: @goal %>
  <div class="my-page__menu--link--bottom">
    <a class="js-modal-open  my-page__link--text" href="" data-target="modal-new-goal">せっていする</a>
  </div>
</div>
<!-- ドキュメント投稿アイコン -->
<div class="my-page__menu--icon js-save-icon">
  <a class="js-modal-open js-save-link" href="" data-target="modal-new-doc">
    <%= image_tag "icon/save-point.png", class: "my-page__menu--icon-img my-page__link--create-doc", alt: "menu-icon" %><br>
    <p class="my-page__link--text">きろくする</p>
  </a>
  <!-- モーダルウインドウ -->
  <%= render "documents/new", document: @document, goals: @goals %>
</div>

app/views/layouts/_validation_errors.html.erb
<% if obj.errors.any? %>
  <div class="error__message">
    <h3><%= pluralize(obj.errors.count,"つの") %>エラーがあります</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li class="error__message--list"><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <title>Dot Diary ~みっかぼうずのやぼう~</title>
    <%= favicon_link_tag('favicon.ico') %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= include_gon %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= yield %>
    <footer class="footer">
      <p class="footer__text">© 2021 DOT DIARY <span>〜 MIKKA BOUZU NO YABOU 〜</span> ALL RIGHTS RESERVED.</p>
    </footer>
    <!-- IEでカスタムプロパティを使用する為のライブラリ -->
    <script src="https://cdn.jsdelivr.net/npm/css-vars-ponyfill@2"></script>
    <!-- IEでobject-fitプロパティを使用する為のライブラリ -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/object-fit-images/3.2.4/ofi.js"></script>
  </body>
</html>